app:
    mock:
        customers:
            count: 1000
        generator:
          threads: 16
            mindelay: 100
          maxdelay: 500
            senderbic: ROYCCAT2
    activemq:
        broker-url: tcp://localhost:61616

