spring:
  datasource:
    url: jdbc:sqlserver://localhost;trustServerCertificate=true
    username: sa
    password: StrongPassword123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:sqlserver://localhost:1433;databaseName=payments;trustServerCertificate=true
    user: sa
    password: StrongPassword123
    schemas: messages
    enabled: false

app:
  active-mq:
    broker-url: tcp://localhost:61616
    user: myactivemquser
    password: myactivemquserpass

  ibm-mq:
    queue-manager: MQ1
    channel: DEV.APP.SVRCONN
    hostname: localhost
    port: 1414
    userid: app
    password: passw0rd

